name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build Signed APK (Maybe unnecessary)
      if: always()
      # You may pin to the exact commit or the version.
      # uses: victorbnl/build-signed-apk@131e59d4deaf2fb9d2aadb555b2ac131affeef5f
      uses: victorbnl/build-signed-apk@v1.0.0
      with:
        # Keystore file encoded as base64
        keystore: ${{ secrets.ANDROID_STORE_KEY }}
        # Keystore file password
        keystore_password: ${{ secrets.GW2L_UPLOAD_STORE_PASSWORD }}
        # Key alias
        key_alias: ${{ secrets.GW2L_UPLOAD_KEY_ALIAS }}
        # Key password
        key_password: ${{ secrets.GW2L_UPLOAD_KEY_PASSWORD }}
        gradlew_dir: android
