name: push-to-play-console
run-name: Publish to Play Console
on:
  workflow_dispatch:
  push:
    branches:
      - add-release-pipeline
    tags:        
      - '*'
env:
  PUBLISH_KEY_PLAYSTORE: ${{ secrets.PUBLISH_KEY_PLAYSTORE }}
jobs:
  push-android:
    defaults:
      run:
        shell: bash
    # needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checking if the aab exists
        run: |
          ls -la
          find . -name *.aab
          ls -l android/app/build/outputs/bundle/release/app-release.aab
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ env.PUBLISH_KEY_PLAYSTORE }}
          packageName: com.scarleshbrihouse.gw2l
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: production
          status: draft